#
# Makefile for Meson SC2 clk
#

obj-$(CONFIG_AMLOGIC_GX_CLK) +=  sc2_clk_secure.o sc2.o sc2_clk_pll.o sc2_clk_mpll.o sc2_secure_clk_mux.o sc2_secure_clk_cpu.o sc2_clk_sdemmc.o sc2_secure_clk_divider.o
