dtb-$(CONFIG_ARM64_A32) += g12b_s922x_minix_u22xj.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_minix_u22xj_max.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_minix_u22xj_max_rev_a.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6_2g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6_4g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6_rev_a_2g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6_rev_a_4g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6b_2g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6b_4g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6b_rev_a_2g.dtb
dtb-$(CONFIG_ARM64_A32) += g12b_s922x_ugoos_am6b_rev_a_4g.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
