#ifndef DECODER_CPU_VER_INFO_H
#define DECODER_CPU_VER_INFO_H

enum AM_MESON_CPU_MAJOR_ID
{
	AM_MESON_CPU_MAJOR_ID_M6 = 0x16,
	AM_MESON_CPU_MAJOR_ID_M6TV = 0x17,
	AM_MESON_CPU_MAJOR_ID_M6TVL = 0x18,
	AM_MESON_CPU_MAJOR_ID_M8 = 0x19,
	AM_MESON_CPU_MAJOR_ID_MTVD = 0x1A,
	AM_MESON_CPU_MAJOR_ID_M8B =  0x1B,
	AM_MESON_CPU_MAJOR_ID_MG9TV = 0x1C,
	AM_MESON_CPU_MAJOR_ID_M8M2 = 0x1D,
	AM_MESON_CPU_MAJOR_ID_UNUSE = 0x1E,
	AM_MESON_CPU_MAJOR_ID_GXBB = 0x1F,
	AM_MESON_CPU_MAJOR_ID_GXTVBB = 0x20,
	AM_MESON_CPU_MAJOR_ID_GXL = 0x21,
	AM_MESON_CPU_MAJOR_ID_GXM = 0x22,
	AM_MESON_CPU_MAJOR_ID_TXL = 0x23,
	AM_MESON_CPU_MAJOR_ID_TXLX = 0x24,
	AM_MESON_CPU_MAJOR_ID_AXG = 0x25,
	AM_MESON_CPU_MAJOR_ID_GXLX = 0x26,
	AM_MESON_CPU_MAJOR_ID_TXHD = 0x27,
	AM_MESON_CPU_MAJOR_ID_G12A = 0x28,
	AM_MESON_CPU_MAJOR_ID_G12B = 0x29,
	AM_MESON_CPU_MAJOR_ID_GXLX2 = 0x2a,
	AM_MESON_CPU_MAJOR_ID_TL1 = 0x2e,
	AM_MESON_CPU_MAJOR_ID_MAX,
};

enum AM_MESON_CPU_MAJOR_ID get_cpu_major_id(void);
#endif
