obj-m	+=	decoder_common.o
decoder_common-objs	+=	utils.o vdec.o vdec_input.o amvdec.o
decoder_common-objs	+=	decoder_mmu_box.o decoder_bmmu_box.o
decoder_common-objs	+=	config_parser.o secprot.o vdec_profile.o
