ifndef CONFIG_ARCH_MESON64_ODROID_COMMON
dtb-y += g12a_s905d2_skt.dtb
dtb-y += g12a_s905d2_skt_buildroot.dtb
dtb-y += g12a_s905d2_u200.dtb
dtb-y += g12a_s905d2_u200_buildroot.dtb
dtb-y += g12a_s905d2_u200_drm_buildroot.dtb
dtb-y += g12b_a311d_w400.dtb
dtb-y += g12b_a311d_w400_buildroot.dtb
endif
dtb-$(CONFIG_ARCH_MESON64_ODROIDC3) += meson64_odroidc3.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2_drm.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += meson64_odroidn2_spibios.dtb
