dtb-y += g12a_s905d2_skt.dtb
dtb-y += g12a_s905d2_skt_buildroot.dtb
dtb-y += g12a_s905d2_u200.dtb
dtb-y += g12a_s905d2_u200_buildroot.dtb
dtb-y += g12a_s905d2_u200_drm_buildroot.dtb
dtb-y += g12a_s905d2_u220.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDC3) += s905d2_odroidc3.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDC3) += s905d2_odroidc3_android.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += s922d_odroidn2.dtb
dtb-$(CONFIG_ARCH_MESON64_ODROIDN2) += s922d_odroidn2_android.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
