dtb-y += g12a_s905x2_2g.dtb
dtb-y += g12a_s905x2_4g.dtb
dtb-y += g12a_s905x2_4g_1gbit.dtb
dtb-y += g12b_s922x_beelink_gt_king.dtb
dtb-y += g12b_a311d_khadas_vim3.dtb
dtb-y += g12b_s922x_odroid_n2.dtb
dtb-y += g12b_s922x_odroid_n2_dvb.dtb
dtb-y += g12b_s922x_odroid_n2_2dvb.dtb
