#
# Makefile for amlogic uvm
#

ccflags-y += -Idrivers/staging/android/ -Idrivers/amlogic/

obj-$(CONFIG_AMLOGIC_UVM_CORE)		+= meson_uvm_core.o meson_uvm_conf.o
obj-$(CONFIG_AMLOGIC_UVM_ALLOCATOR)	+= meson_uvm_allocator.o
obj-$(CONFIG_AMLOGIC_ION_DELAY_ALLOC)	+= meson_ion_delay_alloc.o
