#
# AMLOGIC VE & CM.
#
obj-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_VECM) += am_vecm.o
am_vecm-objs := amve.o
am_vecm-objs += amcm.o
am_vecm-objs += amcsc.o
am_vecm-objs += amcsc_pip.o
am_vecm-objs += amvecm.o
am_vecm-objs += keystone_correction.o
am_vecm-objs += bitdepth.o
am_vecm-objs += set_hdr2_v0.o
am_vecm-objs += dnlp_cal.o
am_vecm-objs += cm2_adj.o
am_vecm-objs += pattern_detection.o
am_vecm-objs += vlock.o
am_vecm-objs += hdr/am_hdr10_plus.o
am_vecm-objs += local_contrast.o
am_vecm-objs += amvecm_drm.o
am_vecm-objs += hdr/am_hdr10_plus_ootf.o
am_vecm-objs += hdr/gamut_convert.o
am_vecm-objs += hdr/am_hdr10_tm.o
am_vecm-objs += ai_pq/ai_pq.o
am_vecm-objs += util/huffman.o
am_vecm-objs += util/base64.o
am_vecm-objs += util/enc_dec.o
am_vecm-objs += cabc_aadc/cabc_aadc_fw.o
am_vecm-objs += hdr/am_hdr10_tmo_fw.o
am_vecm-objs += blue_stretch/blue_str.o
am_vecm-objs += hdr/am_cuva_hdr_tm.o
