obj-$(CONFIG_AMLOGIC_MEDIA_VDEC_H264) += amvdec_h264.o
amvdec_h264-objs += vh264.o

obj-$(CONFIG_AMLOGIC_MEDIA_VDEC_H264_MVC) += amvdec_h264mvc.o
amvdec_h264mvc-objs += vh264_mvc.o

obj-$(CONFIG_AMLOGIC_MEDIA_VDEC_H264_4K2K) += amvdec_h264_4k2k.o
amvdec_h264_4k2k-objs += vh264_4k2k.o
