#Ascending by module name's ASCII
obj-y	+=	arch/
obj-$(CONFIG_AMLOGIC_MEDIA_CANVAS)	+=	canvas/
obj-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM)	+=	codec_mm/
obj-$(CONFIG_AMLOGIC_ION)			+= ion_dev/
obj-$(CONFIG_AMLOGIC_MEDIA_GE2D)	+=	ge2d/
obj-$(CONFIG_AMLOGIC_MEDIA_RDMA)	+=	rdma/
obj-$(CONFIG_AMLOGIC_UVM_CORE)		+=	uvm/
obj-$(CONFIG_AMLOGIC_MEDIA_VFM)	+=	vfm/
obj-$(CONFIG_AMLOGIC_VPU)	+=	vpu/
obj-$(CONFIG_AMLOGIC_VIDEOBUF_RESOURCE)	+= v4l_util/
obj-$(CONFIG_AMLOGIC_MEDIA_LUT_DMA)	+= lut_dma/
obj-$(CONFIG_AMLOGIC_MEDIA_RESMANAGE)	+=	resource_mgr/
