#
# Makefile for LDIM.
#
obj-$(CONFIG_AMLOGIC_LOCAL_DIMMING) = aml_ldim.o ldim_dev_drv.o ldim_spi.o\
		global_bl.o
obj-$(CONFIG_AMLOGIC_LOCAL_DIMMING_IW7027) = iw7027_bl.o
obj-$(CONFIG_AMLOGIC_LOCAL_DIMMING_IW7038) = iw7038.o
aml_ldim-objs := ldim_drv.o ldim_func.o ldim_hw.o ldim_fw_param.o ldim_debug.o
